name: Auto Bluesky Post

on:
  schedule:
    - cron: "0 4,16 * * *"  # Runs at 10 AM & 10 PM IST (4:30 hours behind UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bluesky Bot
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python main.py  # Change this to your actual script filename
